services:
  dev:
    container_name: zimpligital_api_dev
    image: zimpligital_api_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
